blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),    
    path("post/", views.PostLV.as_view(), name="post_list"),    
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),    
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"), 
    
    # ---archive
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
]

    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),

bookmark/urls.py
from django.urls import path
from . import views

app_name = 'bookmark'

urlpatterns = [
    path("", views.BookmarkLV.as_view(), name="index"),
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
]

blog/models.py
from django.db import models
from django.urls import reverse

# id, title, slug, description, content, create_dt, modify_dt

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=100)
    slug = models.SlugField(verbose_name='SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, help_text='simple text')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
            verbose_name = 'post'
            verbose_name_plural = 'posts'
            db_table = 'blog_posts'
            ordering = ('-modify_dt' , )
        
    def __str__(self):
          return self.title
    # +""+ self.url
    def get_absolute_url(self):
          return reverse('blog:post_detail', args=(self.slug,  ))
    def get_previous(self):
          return self.get_previous_by_modify_dt()
    def get_next(self):
          return self.get_next_by_modify_dt()

bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark (models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title+"  "+ self.url
    

blog/views.py
from django.shortcuts import render
from .models import Post
# from django.views.generic import *
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html' #blog/post_list.html
    context_object_name = 'posts' #post_list
    paginate_by = 1
    
class PostDV(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive.html"

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    template_name = "blog/post_archive_year.html"

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_month.html"

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

# ListView
class BookmarkLV(ListView):
    model=Bookmark

    # template_name = 'bookmark/bookmark_list.html' #[app_name]/[model_name]_list.html
    # context_object_name = 'object_list' #object_list

# DetailView
class BookmarkDV(DetailView):
    model=Bookmark
    # template_name = 'bookmark/bookmark_detail.html' #[app_name]/[model_name]_detail.html
        # context_object_name = 'object' #object

config/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog: Post{% endblock %}
{% block content %}

<h3>Blog: Post List</h3>
<br>
{% for post in posts %}
<h5>제목: <a href={% url 'blog:post_detail' post.slug %}>{{post.title}}</a> </h5>
{#<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a> </h3> #}
<h6>날짜: {{post.modify_dt | date:"Y년 n월 d일" }}</h6>
<p>내용: {{post.content}}</p>
{% endfor %}


<div class="card">
    <img src="kakao" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</a> </h5></h5>
      <p class="card-text">{{post.content}}</p>
      <a href="#" class="btn btn-primary">전체보기</a>
    </div>
  </div>
  
  <div class="card" aria-hidden="true">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title placeholder-glow">
        <span class="placeholder col-6"></span>
      </h5>
      <p class="card-text placeholder-glow">
        <span class="placeholder col-7"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-6"></span>
        <span class="placeholder col-8"></span>
      </p>
      <a class="btn btn-primary disabled placeholder col-6" aria-disabled="true"></a>
    </div>
  </div>


<br>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>



<script>
    function loadPage(pageNumber) {
      // 여기에 페이지 내용을 불러오는 코드를 작성합니다.
      // 예를 들어, AJAX를 사용하여 페이지 내용을 가져올 수 있습니다.
      // 이 예제에서는 페이지 번호만 콘솔에 출력합니다.
      console.log("Loading page", pageNumber);
      // 여기에 실제 페이지 내용을 업데이트하는 코드를 추가하세요.
    }
  </script>
  
  <nav aria-label="...">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" onclick="loadPage({{ page_obj.previous_page_number }})">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      {% endif %}
      <li class="page-item{% if page_obj.number == 1 %} active{% endif %}">
        <a class="page-link" href="?page=1" onclick="loadPage(1)">1</a>
      </li>
      <li class="page-item{% if page_obj.number == 2 %} active{% endif %}">
        <a class="page-link" href="?page=2" onclick="loadPage(2)">2</a>
      </li>
      <li class="page-item{% if page_obj.number == 3 %} active{% endif %}">
        <a class="page-link" href="?page=3" onclick="loadPage(3)">3</a>
      </li>
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" onclick="loadPage({{ page_obj.next_page_number }})">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  



{% endblock %}

blog/templates/blog/post_archive.html
<h1>Archive List {% now "Y m d" %}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_year_archive' date|date:'Y' %}"> Year-{{date|date:'Y'}} </a></li>
    {% endfor %}
</ul>

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}} 
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{{date_list}}

{{object_list}}

blog/templates/blog/post_archive_day.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{year|date:"Y"}}</h1>

<ul>
    {% for post in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b'%}"> Year-{{date|date:'F'}}</a></li>
    {% endfor %}
</ul>

{# m : 04, F : April, M : Apr, b : apr #}

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{{date_list}}
{{object_list}}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bookmark List{% endblock %}
{% block content %}

<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
        &laquo;-- {{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
    {{ object.get_next }} --&raquo;
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>

{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}

<h1>Title: {{object.title}}</h1>
<br>
<h3>URL: <a href="{{object.url}}">{{object.url}}</a> </h3>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
<h1>Bookmark List</h1>
<br>
<ul class="list-group">
    {% for bookmark in object_list %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark.title }}</a>
        <span class="badge text-bg-primary rounded-pill">1</span>
        </li>
  
    {% endfor %}
</ul>

{% endblock %}


{#<li><a href= "{% url 'bookmark:index' %}">{{bookmark.title}}</a></li>#}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Mini Cafe {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    {% block extra-style %}
    <style type="text/css">
      .home-image {
          background-image: url("{% static 'image/lion.jpg' %}");
          background-repeat: no-repeat;
          background-position: center;
          background-size: 100%;
          height: 500px;
          border-top: 10px solid #ccc;
          border-bottom: 10px solid #ccc;
          padding: 20px 0 0 20px;
      }
      .title {
          color: #c80;
          font-weight: bold;
      }
      .powered {
          position: relative;
          top: 77%;
          color: #cc0;
          font-style: italic;
      }
      </style>
      {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">

        <div class="container-fluid">

          <a class="navbar-brand mx-5 mb-10 fw-bold fst-italic" href="#">Python Web Programming</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'bookmark:index' %}">Bookmark</a>
              </li>
          
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
              </li>
          
              <li class="nav-item">
                <a class="nav-link" href="#">Photo</a>
              </li>
          
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Util
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                  <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Search</a></li>
                </ul>
              </li>
          
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

          </div>

        </div>

      </nav>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    {% block footer %}
    <footer class="fixed-bottom">
        <h4> This is Footer area. </h4>
    </footer> 
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>

</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Home Template{% endblock %}

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'image/lion.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
    </style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Python web Programming !!</h2>
</div>
<div class="row" text-center>
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>
            Bookmark is a Uniform Resource Identifier (URI) that is stored for later retrieval in any of various storage formats. you can store your own
        </p>
    </div>

    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>
            Bookmark is a Uniform Resource Identifier (URI) that is stored for later retrieval in any of various storage formats. you can store your own
        </p>
    </div>
</div>

{% endblock %}